package com.mall.xiaomi.entry;

public class GoodsImages {
    @Override
    public String toString() {
        return "GoodsImages{" +
                "id=" + id +
                ", path='" + path + '\'' +
                ", title='" + title + '\'' +
                ", alt='" + alt + '\'' +
                ", goodsId=" + goodsId +
                '}';
    }

    public GoodsImages() {
    }

    public GoodsImages(String path, String title, String alt, Integer goodsId) {
        this.path = path;
        this.title = title;
        this.alt = alt;
        this.goodsId = goodsId;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_images.id
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_images.path
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_images.title
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_images.alt
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    private String alt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_images.goods_id
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    private Integer goodsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_images.id
     *
     * @return the value of goods_images.id
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_images.id
     *
     * @param id the value for goods_images.id
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_images.path
     *
     * @return the value of goods_images.path
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_images.path
     *
     * @param path the value for goods_images.path
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_images.title
     *
     * @return the value of goods_images.title
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_images.title
     *
     * @param title the value for goods_images.title
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_images.alt
     *
     * @return the value of goods_images.alt
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    public String getAlt() {
        return alt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_images.alt
     *
     * @param alt the value for goods_images.alt
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    public void setAlt(String alt) {
        this.alt = alt == null ? null : alt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_images.goods_id
     *
     * @return the value of goods_images.goods_id
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_images.goods_id
     *
     * @param goodsId the value for goods_images.goods_id
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }
}