package com.mall.xiaomi.entry;

import java.util.Date;

public class GoodsOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_order.id
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    private String id;

    public GoodsOrder(String id, Date orderDate, Integer consumerId, String status, String goodsShippingAddressId) {
        this.id = id;
        this.orderDate = orderDate;
        this.consumerId = consumerId;
        this.status = status;
        this.goodsShippingAddressId = Integer.valueOf(goodsShippingAddressId);
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_order.order_date
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    private Date orderDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_order.consumer_id
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    private Integer consumerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_order.status
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_order.goods_shipping_address_id
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    private Integer goodsShippingAddressId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_order.id
     *
     * @return the value of goods_order.id
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_order.id
     *
     * @param id the value for goods_order.id
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_order.order_date
     *
     * @return the value of goods_order.order_date
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_order.order_date
     *
     * @param orderDate the value for goods_order.order_date
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_order.consumer_id
     *
     * @return the value of goods_order.consumer_id
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    public Integer getConsumerId() {
        return consumerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_order.consumer_id
     *
     * @param consumerId the value for goods_order.consumer_id
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    public void setConsumerId(Integer consumerId) {
        this.consumerId = consumerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_order.status
     *
     * @return the value of goods_order.status
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_order.status
     *
     * @param status the value for goods_order.status
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_order.goods_shipping_address_id
     *
     * @return the value of goods_order.goods_shipping_address_id
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    public Integer getGoodsShippingAddressId() {
        return goodsShippingAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_order.goods_shipping_address_id
     *
     * @param goodsShippingAddressId the value for goods_order.goods_shipping_address_id
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    public void setGoodsShippingAddressId(Integer goodsShippingAddressId) {
        this.goodsShippingAddressId = goodsShippingAddressId;
    }


}