package com.mall.xiaomi.dao;

import com.mall.xiaomi.entry.GoodsOrderItem;
import com.mall.xiaomi.entry.GoodsOrderItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsOrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order_item
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    long countByExample(GoodsOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order_item
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    int deleteByExample(GoodsOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order_item
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order_item
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    int insert(GoodsOrderItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order_item
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    int insertSelective(GoodsOrderItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order_item
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    List<GoodsOrderItem> selectByExample(GoodsOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order_item
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    GoodsOrderItem selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order_item
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    int updateByExampleSelective(@Param("row") GoodsOrderItem row, @Param("example") GoodsOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order_item
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    int updateByExample(@Param("row") GoodsOrderItem row, @Param("example") GoodsOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order_item
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    int updateByPrimaryKeySelective(GoodsOrderItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order_item
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    int updateByPrimaryKey(GoodsOrderItem row);
}