package com.mall.xiaomi.dao;

import com.mall.xiaomi.entry.GoodsShippingAddress;
import com.mall.xiaomi.entry.GoodsShippingAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsShippingAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shipping_address
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    long countByExample(GoodsShippingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shipping_address
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    int deleteByExample(GoodsShippingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shipping_address
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shipping_address
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    int insert(GoodsShippingAddress row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shipping_address
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    int insertSelective(GoodsShippingAddress row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shipping_address
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    List<GoodsShippingAddress> selectByExampleWithBLOBs(GoodsShippingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shipping_address
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    List<GoodsShippingAddress> selectByExample(GoodsShippingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shipping_address
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    GoodsShippingAddress selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shipping_address
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    int updateByExampleSelective(@Param("row") GoodsShippingAddress row, @Param("example") GoodsShippingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shipping_address
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("row") GoodsShippingAddress row, @Param("example") GoodsShippingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shipping_address
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    int updateByExample(@Param("row") GoodsShippingAddress row, @Param("example") GoodsShippingAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shipping_address
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    int updateByPrimaryKeySelective(GoodsShippingAddress row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shipping_address
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(GoodsShippingAddress row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shipping_address
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    int updateByPrimaryKey(GoodsShippingAddress row);
}