package com.mall.xiaomi.dao;

import com.mall.xiaomi.entry.GoodsCart;
import com.mall.xiaomi.entry.GoodsCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_cart
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    long countByExample(GoodsCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_cart
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    int deleteByExample(GoodsCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_cart
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_cart
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    int insert(GoodsCart row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_cart
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    int insertSelective(GoodsCart row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_cart
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    List<GoodsCart> selectByExample(GoodsCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_cart
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    GoodsCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_cart
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    int updateByExampleSelective(@Param("row") GoodsCart row, @Param("example") GoodsCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_cart
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    int updateByExample(@Param("row") GoodsCart row, @Param("example") GoodsCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_cart
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    int updateByPrimaryKeySelective(GoodsCart row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_cart
     *
     * @mbg.generated Sun May 22 23:33:15 CST 2022
     */
    int updateByPrimaryKey(GoodsCart row);
}